name: Publish Package to npmjs
on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@elastic'
      - run: yarn
      - run: yarn publish
        env:
          NPM_CONFIG_PROVENANCE: true
